<?php 
return array (
  'cache' => '0',
  'cookie_domain' => '',
  'dateFormat' => 'd.m.Y',
  'dateTimeFormat' => 'd.m.Y - H:i',
  'debug' => '1',
  'defaultDescription' => '',
  'defaultEmail' => '',
  'defaultKeywords' => '',
  'defaultLocale' => 'en',
  'defaultTheme' => 'default',
  'defaultTitle' => 'Mo3D',
  'is_production' => '0',
  'is_console' => '1',
  'host' => 'test.getoutlines.com',
  'locale' => 'en,fr',
  'mediaSrc' => 'https://getoutlines.com',
  'protocol' => 'https://',
  'searchEngine' => 'sphinx',
  'sendEmailOnException' => '0',
  'smtp_from' => 'Mo3D',
  'smtp_login' => 'support@getoutlines.com',
  'smtp_password' => '12345',
  'smtp_port' => '587',
  'smtp_server' => 'getoutlines.com',
  'timeDateFormat' => 'H:i - d.m.Y',
  'timeFormat' => 'H:i',
  'timezoneSet' => 'UTC',
  'userControl' => '',
  'userDb' => '',
)
?>
